apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-mysql-db
spec:
  selector:
    matchLabels:
      app: netflix-mysql-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: netflix-mysql-db
    spec:
      containers:
      - name: netflix-mysql-db
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: YWRtaW4xMjM=
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes: # We are mounting for our container one volume
        - name: mysql-persistent-storage
          persistentVolumeClaim: 
            claimName: pvc-mysql-netflix #same name as PVC else scheduling will fail
---

apiVersion: v1
kind: Service
metadata:
  name: netflix-mysql-svc
spec:
  selector:
    app: netflix-mysql-db
  ports:
  - port: 3306
  clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-netflix
  labels: 
    app: netflix-mysql-db
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc-mysql-netflix
  accessModes:
    - ReadWriteOnce