# First self made docker file to run on docker 
FROM python:alpine

WORKDIR /app/netflix

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install django && \
pip install django-allauth && \
python -m pip install Pillow && \
python manage.py migrate && \
python manage.py runserver

EXPOSE 8000

#CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]