apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-demo-deployment 
  labels: 
    app: hpa-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-nginx
  template:
    metadata:
      labels:
        app: hpa-nginx
    spec:
      containers:
      - name: hpa-nginx
        image: registry.k8s.io/hpa-example
        resources:
          requests: # must be less than or equal to cpu limit
            cpu: "100m"
          limits:
            cpu: "200m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: hpa-svc
spec:
  type: NodePort
  selector:
    app: hpa-nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31231
